# Generated by Django 2.1.3 on 2018-12-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181204_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.TextField(default='img/patients/def_patient.jpeg', max_length=250),
        ),
    ]
