# Generated by Django 2.1.3 on 2018-12-02 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutInfo', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=250)),
                ('clinic_address', models.CharField(max_length=250)),
                ('clinic_phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+\\d{8,15}$')])),
                ('clinic_email', models.CharField(max_length=250)),
            ],
        ),
    ]
