# Generated by Django 2.1.3 on 2018-12-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.CharField(default='img/', max_length=250),
            preserve_default=False,
        ),
    ]
